### ISSUE TITLE
Create visualization for the dataset/variables

### ISSUE THREAD

**Issue by qubixes** [sodascience/metasyn#101]
There is a lot to be gained with visualizations of the original data, and the synthetic data.

Perhaps it is an idea as well to allow these visualizations to be implemented as plugins as well?

**Comment by vankesteren** [comment]
Two thoughts:

1. This is a little bit feature creep. We might refer to something like [`sdv.evaluation`](https://docs.sdv.dev/sdv/single-table-data/evaluation#visualization) for this
2. It is essential to do this to determine how well the synthetization has worked.

Maybe we can decide how to go about this as part of the pilot project with YOUth?
