### ISSUE TITLE
update docstrings for 0.4.0 

### ISSUE THREAD

**Issue by Samuwhale** [sodascience/metasyn#138]
Docstrings have to be updated to represent new naming schemes

**Comment by qubixes** [comment]
I forgot exactly what this entails, can you elaborate?

**Comment by Samuwhale** [comment]
Yeah, maybe a more fleshed out description would have been nice oops. But, if I remember correctly, this was right after we did the 'metaframe' rename, so this entails the renaming of 'MetaSynth dataset' to 'Metaframe'. 

I know I renamed a few of the docstrings already in #162 as a little extra, but there _might_ be an instance or two of the old naming left still.

**Comment by qubixes** [comment]
Right, I seem to remember now. I have done some renaming of MetaDataset -> MetaFrame, and Dataset -> MetaFrame, so I'll consider this closed then.
