### ISSUE TITLE
Phone Number Metadata

### ISSUE THREAD

**Issue by Mrin7** [sodascience/metasyn#140]
@qubixes 
This is what the metadata for phone number column looks like. This metadata was created when I used "metadata = MetaDataset.from_dataframe(df)"
{
            "name": "emp_phone_no",
            "type": "continuous",
            "dtype": "Float64",
            "prop_missing": 0.23655913978494625,
            "distribution": {
                "implements": "core.exponential",
                "provenance": "builtin",
                "class_name": "ExponentialDistribution",
                "parameters": {
                    "rate": 3.1744290032716335e-07
                }
            }
        },

Can you please share instruction on how I can create metadata manually for Phone number, name, email id ,ssn, credit_card_number so that it fetches samples from faker? As we can see in this example, the code in the backend is translating phone number as exponential continuous distribution.
My intention is to pass "metadata.json" file to synthesize data for various columns."synthetic_data = metadata.synthesize(500) "

The outputs that I am getting from synthesize function, does not resemble phone numbers at all.
Eg:
617914.509611
3.2832e6
null
495603.009907

**Comment by vankesteren** [comment]
Hey @Mrin7, great to see that you're actively using MetaSynth!

You have probably noticed that we are still actively developing this software, and it will become more stable over the coming months. The answer to your question is not yet in the official documentation, but you can find it here: 

https://github.com/sodascience/metasynth/blob/main/examples/advanced_tutorial.ipynb

in short, either manually specify a RegexDistribution with regex "\d{9}", or specify a FakerDistribution with "phone_number" as its provider. 

How to do this can be found in the section "Specifying the distribution of structured strings".

**Comment by qubixes** [comment]
Hi @Mrin7,

It seems like the column you're trying to synthesize has the wrong data type. Are you using pandas or polars to create the dataframe? With pandas, be sure to convert the column to a nullable integer type, otherwise you'll get floating point numbers. Hope that helps.
