### ISSUE TITLE
RENAME MetaSynth -> metasyn

### ISSUE THREAD

**Issue by vankesteren** [sodascience/metasyn#149]
How about removing capitalization of the package name in our communication about this package?

1. Our logo does not have capitalization
2. We don't want to imply any association with the company Meta
3. Capitalization is more effort
4. When you import our package, you don't capitalize
5. I like it better :)

We could choose to capitalize if we start a sentence with the package name, i.e.:
> Metasynth is a python package to generate synthetic data.

but also

> Advanced options in metasynth allow you to customize how the synthetic data generation happens

what do you think @Samuwhale & @qubixes?

**Comment by Samuwhale** [comment]
I agree :)

That said, it also got me searching around, which resulted in me stumbling across a whole new issue...

There is a currently existing audio software, named [MetaSynth](https://uisoftware.com/MetaSynth/). Sure, going lowercase would technically differentiate us from them. But even then I'm not sure about the legalities. Is it okay for us to share the names? Besides legalities, it also impacts the findability of our package when searching for it by name.

**Comment by qubixes** [comment]
@Samuwhale Yeah, it might be nice to have a distinctive name. I'm not a legal scholar, so I don't really know about legal issues.

Would be interesting to think of a new name, don't really have any suggestions right now though, especially if "meta" is out...

**Comment by vankesteren** [comment]
Of course, I'm not a lawyer, but I think we may be fine keeping the name. There is very little risk of confusing the two software products because they do wildly different things. Removing the capitalization might actually help with this. 

On the other hand, it is of course safer to change the name; We might append something to the end (I think `metasynthe` could work, it's pronounced the same and implies "synthesis") or take some letters away (`metasyn` is nice and short, alternatively `metasynt`)

The audio software trademark is registered (see [here](https://tmsearch.uspto.gov/bin/showfield?f=doc&state=4809:ayzhd0.2.1)) but although its description includes "computer software", it does not include our use. 

Some relevant answers are [here](https://law.stackexchange.com/a/13434) and [here](https://law.stackexchange.com/a/3409), with some more info [here](https://www.iusmentis.com/trademarks/crashcourse/rights/).

**Comment by vankesteren** [comment]
@Samuwhale, @qubixes, we need to decide on this ASAP with the interview coming out soon.

**Comment by Samuwhale** [comment]
I think, seeing as it probably is not a legal issue, that 'metasynth' is the nicest. 

That said, if we do want to pick a 'safe' option, it's probably smartest to go for a longer name (like metasynthe) instead of shortening it (metasyn) as making it longer makes it more specific and improves Google search results, whereas shortening it would bury us under the audio software's search results.

**Comment by bagheria** [comment]
Hey guys,
Just to jump into the conversation, I would like to say that it might be better to go beyond just lowercase. The suggestions (metasynt and metasynthe) are good ones and I am not worried about the Google search. I also asked chatgpt and here are some more suggestions:
PrivySynth
PrivacySynthetix
MetaMystic
SecureSynth
DifferSynth
PrivataSynth
SafeMetaForge
PrivyMixer
SynthoGuard
DifferMetaMaker
PrivySynth
PrivacySynthetix
MetaMystic
SecureSynth
DifferSynth
PrivataSynth
SafeMetaForge
PrivacyCraft
MetaBlendGuard
DigiCloak
MetaPrivacyWiz
PrivyMixer
PrivacyFusion
SynthoGuard
MetaPrivacyCraft
DataFortify
MetaSynthGuard
MetaSynthProtec
SecureMetaSynth
MetaPrivacySynth
PrivyMetaSynth

**Comment by vankesteren** [comment]
Decision: rename to metasyn. Only capitalize if at beginning of a sentence

**Comment by vankesteren** [comment]
To-do:

- [ ] update pypi @qubixes 
- [ ] update documentation @Samuwhale 
- [ ] update repo name @vankesteren 
- [ ] update docker image @vankesteren 
- [ ] send message to interviewer @vankesteren

**Comment by vankesteren** [comment]
Yes, it will be one big PR hopefully
