### ISSUE TITLE
Add an additional function named 'export'

### ISSUE THREAD

**Issue by Samuwhale** [sodascience/metasyn#160]
I discussed with @qubixes and we agreed on more consistent usage of the term 'GMF file' as opposed to the longer, and sometimes more vague 'MetaFrame exported to JSON', but in line with this, it might be nice to add a new `export` function.

It could simply be a wrapper function around `to_json`, it does not have to replace it. 

It's a very simple addition, but would avoid having to use confusing sentences in the docs along the lines of 'you can export a metaframe to a gmf file with `to_json`' and instead facilitate more a more natural 'you can export a metaframe to a gmf file with `export`'.

**Comment by vankesteren** [comment]
great idea.
