### ISSUE TITLE
Replace flake8 with ruff

### ISSUE THREAD

**Issue by qubixes** [sodascience/metasyn#178]
I don't know exactly why `_version.py` is found by flake8, but since flake8 doesn't support pyproject.toml, we might want to switch to ruff so we can ignore the file there.

**Comment by vankesteren** [comment]
yes! finally! I had secretly been using ruff already locally ;)

Let's create a good ruff config in pyproject, and then we can also remove pylint I think

**Comment by Samuwhale** [comment]
I'll look into it! :)
