### ISSUE TITLE
Review the documentation

### ISSUE THREAD

**Issue by qubixes** [sodascience/metasyn#184]
Before we create 1.0, we should have a big review on the documentation and see what can be improved.

**Comment by vankesteren** [comment]
Should comply completely with https://joss.readthedocs.io/en/latest/review_criteria.html#documentation

**Comment by qubixes** [comment]
Adding issues here while I'm reading the documentation:

- Detailed overview should be it's own section and not under about. Perhaps I would also give it a different name, but for now it's okay.
- About section should be the last.
- On metasyn in detail, it isn't clear immediately that the example can be expanded. Perhaps an [expand] notification could be helpful.

**Comment by qubixes** [comment]
I'm done with my review. How do we want to do this? Implement/repair, or discuss first?

**Comment by Samuwhale** [comment]
I'll be starting my review today and tomorrow too!

@qubixes could you maybe check off or strike a line through points that have been implemented (or are in a PR atm)? I think that would help with adding some overview to the progress.

**Comment by qubixes** [comment]
@Samuwhale All of the suggestions are my PR already.

**Comment by Samuwhale** [comment]
> @Samuwhale All of the suggestions are my PR already.

Check! I thought so already, but wasn't 100% sure if all the points were tackled.

**Comment by qubixes** [comment]
All done now!
