### ISSUE TITLE
Fix `lengths` deprecation warning in regexmodel/regexclass.py:321

### ISSUE THREAD

**Issue by Samuwhale** [sodascience/metasyn#197]
When fitting a df using a regex distribution, the output log is spammed with deprecation warnings. 

`.../regexmodel/regexclass.py:321: DeprecationWarning: `lengths` is deprecated. It has been renamed to `len_bytes`.
  avg_len_next = next_series.drop_nulls().str.lengths().mean()`

EDIT: I realise this is an issue with the [regexmodel](https://github.com/sodascience/regexmodel), should I move the issue to that repo?

**Comment by qubixes** [comment]
@Samuwhale Yes, but I have made a new release that should have fixed it now. Let me know if it somehow isn't fixed.
