### ISSUE TITLE
Internal provider naming of distributions with variable types

### ISSUE THREAD

**Issue by vankesteren** [sodascience/metasyn#218]
Currently, we sometimes have a distribution that works for different data types. Motivating example is the uniform distribution. We currently name them (for the distribution provider):

- `core.uniform` (for continuous variables)
- `core.discrete_uniform` (for discrete variables)
- `core.uniform_datetime` (for datetime variables)

Two points: 

1. I don't really like that we have to put the data type in the name while the data type is also a property of the distribution itself, seems to go against DRY
2. There is inconsistency in where we put the data type. 

Let's at least agree on the following proposal which solves point 2: 

__if you include data type, always put it after the distribution name__

So for uniform it will be:

- `core.uniform`
- `core.uniform_discrete`
- `core.uniform_datetime`

(looks more uniform 😉)

An added benefit is that we can put additional modifiers (which according to my point 1 also don't belong in the name but in the properties) in front of the distribution, yielding stuff like:

- `core.unique_uniform`

**Comment by Samuwhale** [comment]
I have noted to put the data type after the distribution name in the WIP dev section of the docs.

That said, I do agree with @qubixes that having a uniform name is probably the neatest.
