### ISSUE TITLE
Check the names of all parameters of distributions.

### ISSUE THREAD

**Issue by qubixes** [sodascience/metasyn#228]
I think all distributions with the same name should have the same parameter names as well. Also, it would be good to make sure we agree on all parameter names before we make 1.0.

**Comment by vankesteren** [comment]
So the way I see it we have quite many names for lower and upper bounds, even after the fix in PR #227 from which this table was generated.

Maybe we can converge on 
`lower, upper`?

**Comment by vankesteren** [comment]
My opinion, feel free to disagree @qubixes and @Samuwhale 


| Distribution | Param names | proposal |
| :-- | :-- | :-- |
| DiscreteNormalDistribution | mean, std_dev | mean, sd |
| DiscreteTruncatedNormalDistribution | lower_bound, upper_bound, mu, sigma | lower, upper, mean, sd |
| DiscreteUniformDistribution | low, high | lower, upper |
| PoissonDistribution | mu | rate |
| UniqueKeyDistribution | low, consecutive | lower, interval |
| UniformDistribution | low, high | lower, upper |
| NormalDistribution | mean, std_dev | mean, sd |
| LogNormalDistribution | mu, sigma | mean, sd |
| TruncatedNormalDistribution | lower_bound, upper_bound, mu, sigma | lower, upper, mean, sd |
| ExponentialDistribution | rate | |
| MultinoulliDistribution | labels, probs | |
| RegexDistribution | regex_data | |
| UniqueRegexDistribution | regex_data | |
| FakerDistribution | faker_type, locale | |
| UniqueFakerDistribution | faker_type, locale | |
| FreeTextDistribution | locale, avg_sentences, avg_words | |
| DateUniformDistribution | start, end | lower, upper |
| TimeUniformDistribution | start, end, precision | lower, upper, precision |
| DateTimeUniformDistribution | start, end, precision | lower, upper, precision |
| ConstantDistribution | value | |
| DiscreteConstantDistribution | value | |
| StringConstantDistribution | value | |
| DateTimeConstantDistribution | value | |
| DateConstantDistribution | value | |
| TimeConstantDistribution | value | |

**Comment by vankesteren** [comment]
Making a to-do list for my upcoming PR
- [ ] DiscreteNormalDistribution
- [ ] DiscreteTruncatedNormalDistribution
- [ ] DiscreteUniformDistribution
- [ ] PoissonDistribution
- [ ] UniqueKeyDistribution
- [ ] UniformDistribution
- [ ] NormalDistribution
- [ ] LogNormalDistribution
- [ ] TruncatedNormalDistribution
- [ ] DateUniformDistribution
- [ ] TimeUniformDistribution
- [ ] DateTimeUniformDistribution

**Comment by vankesteren** [comment]
Oops

![image](https://github.com/sodascience/metasyn/assets/11596858/ebf8822c-1a72-4b22-9b6b-869f2a4cfa7d)

**Comment by vankesteren** [comment]
Getting there...

![image](https://github.com/sodascience/metasyn/assets/11596858/0105edde-5110-428a-b8a7-5cf869bd6151)
