### ISSUE TITLE
Link to templates from documentation

### ISSUE THREAD

**Issue by qubixes** [sodascience/metasyn#233]
I have made an update to the metasyn plugin template, and created a new template. My idea is that there should be two different templates:

- Privacy plugin -> https://github.com/sodascience/metasyn-plugin-template -> should be renamed metasyn-privacy-template. This plugin is there to create a new privacy package (such as a differential privacy package).
- Distribution plugin -> https://github.com/sodascience/metasyn-distribution-template. This plugin is there to create a new distribution that is not implemented in the core package (such as a LLM model).

This should be reflected in the documentation as well. I think some of the documentation there can than be moved to the documentation of the template itself.

**Comment by Samuwhale** [comment]
Looks good, will apply the changes :)

**Comment by Samuwhale** [comment]
Solved in #235
