### ISSUE TITLE
IMPORTANT: fix unfriendly user interface for var specs

### ISSUE THREAD

**Issue by vankesteren** [sodascience/metasyn#240]
I think our new `var_specs` interface is unnacceptably unfriendly to new users.

## Old situation

https://github.com/sodascience/metasyn/blob/516772381741339cf409d4cc13ccbe2f094f4b2d/examples/basic_example.py#L3

https://github.com/sodascience/metasyn/blob/516772381741339cf409d4cc13ccbe2f094f4b2d/examples/basic_example.py#L23-L26

https://github.com/sodascience/metasyn/blob/516772381741339cf409d4cc13ccbe2f094f4b2d/examples/basic_example.py#L29

## Current situation

https://github.com/sodascience/metasyn/blob/73c78813144b2a85043eda0e01d9ac774d0fbdab/examples/basic_example.py#L3-L5

https://github.com/sodascience/metasyn/blob/73c78813144b2a85043eda0e01d9ac774d0fbdab/examples/basic_example.py#L25-L28

https://github.com/sodascience/metasyn/blob/73c78813144b2a85043eda0e01d9ac774d0fbdab/examples/basic_example.py#L36

## Options

We need to give starting users more simplicity. 

Options:
- Write conversion method from dict to list of varconfigs that gets called automatically
- Export varconfig in metasyn so you only need one import line AND unnest varconfig / distributionspec so we don't need to ALSO import DistributionSpec. It's really too nested now for users. 

Let's discuss how to fix this

**Comment by qubixes** [comment]
There is no technical problem here:
```python
MetaFrame.fit_dataframe(df, var_specs=[{"name": "PassengerId", "dist_spec": {"unique": True}}])
```
Should give the same results. So it's more how we want to present it in the tutorial. Personally I prefer the import route, because it is more explicit in what actually happens and less chance to mess up something in the dictionary (by misspelling). Unnesting could be an option, but I kind of do feel the nesting makes sense..

**Comment by vankesteren** [comment]
@qubixes and I just had a brainstorm and we propose about the following UI (ignore the ugly type annotations included for our memory):

```py

from metasyn import MetaFrame, VarSpec as VS, demo_dataframe
from metasyn.distribution import MultinoulliDistribution, PoissonDistribution
from metasyn.privacy import BasicPrivacy
from metasyncontrib.disclosure import DisclosurePrivacy

my_df = demo_dataframe("fruit")
not_sensitive = BasicPrivacy()
my_var_specs = [
    VS("ID", distribution="uniform", unique=True),
    VS("fruits", distribution=MultinoulliDistribution),
    VS("B", privacy=not_sensitive, unique=False),
    VS("cars", privacy=not_sensitive),
    VS("newcolumn", distribution=PoissonDistribution(1), data_free=True),
]

mf = MetaFrame.fit_dataframe(
    df: DataFrame = my_df,
    var_specs: List[VarSpec] | Path | str | MetaConfig | None = my_var_specs,
    privacy: BasePrivacy | dict | None = DisclosurePrivacy(n_avg=11),
    n_rows: int | None = None,
    dist_providers: list[str] | None = None
)
```

@Samuwhale we'll discuss this next week, if you have any thoughts in the meantime let us know

**Comment by Samuwhale** [comment]
This looks really nice, looking forward to hearing more on monday!
