### ISSUE TITLE
Update readme for better landing experience

### ISSUE THREAD

**Issue by vankesteren** [sodascience/metasyn#241]
This is one of the tasks in #184 

- shorter, to the point readme with a single simple example (e.g., as in https://github.com/sodascience/metasyn/blob/main/examples/basic_example.py or even simpler) 
- it should be immediately clear upon landing on our page what / who this is for, even to outside people who have no clue! Something around transparent, understandable, and privacy-friendly synthetic tabular data for code testing, open science, accessibility, reproducibility, reuse. Possibly with nice formatting / lists with emojis

**Comment by vankesteren** [comment]
Can you make a proposal / PR @Samuwhale?

**Comment by Samuwhale** [comment]
Closing this issue as I think the readme is in a good place again!
