### ISSUE TITLE
Support latest version of polars

### ISSUE THREAD

**Issue by vankesteren** [sodascience/metasyn#243]
part of #230 

wasn't sure whether this was planned already but I think we should aim for supporting the latest version of things as much as possible

**Comment by qubixes** [comment]
If I remember correctly, the current cycle is to get to 1.0. I think then waiting for 1.0 is a reasonable goal (since it's rather unstable at the moment).

**Comment by vankesteren** [comment]
1.0 of polars? Do you know when the ETA of that is?

**Comment by qubixes** [comment]
Yes, as far as I remember. I don't know when that is, but I think I read in the release notes that 0.20.x is kind of like an alpha branch for the first 1.0 release.

**Comment by qubixes** [comment]
https://github.com/pola-rs/polars/releases/tag/py-0.20.0
