### ISSUE TITLE
macOS ci build often fails on nbval

### ISSUE THREAD

**Issue by vankesteren** [sodascience/metasyn#263]
See for example here: https://github.com/sodascience/metasyn/actions/runs/8066127477/job/22033475174

A rerun often fixes it. But it takes 37 minutes off our budget every time so that's very wasteful! We should either fix this or turn off macOS builds for now

**Comment by qubixes** [comment]
They haven't been failing since the polars update. Let's see if it keeps succeeding.

**Comment by vankesteren** [comment]
it happened again! https://github.com/sodascience/metasyn/actions/runs/8085911882/job/22094465676?pr=264
