### ISSUE TITLE
Improve error messages and warnings

### ISSUE THREAD

**Issue by vankesteren** [sodascience/metasyn#265]
In each of our steps (fit_dataframe, export, from_json, synthesize) it would be nice to think a bit more about friendly and helpful error messages. Especially in the first one, it's very important to attend users to the different options. Also, we used to have this warning for unique values which is now gone?

I feel like this is an area where we can look at the tidyverse once again. Let's think about what can go wrong for the user in each of these steps and come up with nice error messages!

**Comment by Samuwhale** [comment]
I would love to taka a look at this!

**Comment by vankesteren** [comment]
I had hoped so 😄 we can use this issue to communicate about this and make some kind of checklist. Maybe it's a good idea to first create some kind of inventory of things that can go wrong / are likely to go wrong before we start writing code. Kind of like what happened here: https://github.com/sodascience/metasyn/issues/228

**Comment by Samuwhale** [comment]
Yep sounds good, I'll get started on it today and throughout the week.

**Comment by Samuwhale** [comment]
Work in progress list of what can go wrong:

**Fitting a metaframe:**
- [ ] Trying to fit to an incompatible input (trying to fit to something that is not a DataFrame)
- [ ] Errors in meta_config
- [ ] Errors in var_spec

**Exporting/Importing a metaframe to file:**
- [ ] 

**Generating synthetic data from the metaframe:**
- [ ]

**Comment by vankesteren** [comment]
For some extra context, here is an example of what I would consider an excellent error message from the `R` package `dplyr`:

![afbeelding](https://github.com/sodascience/metasyn/assets/11596858/85637d09-7be5-47cc-b91a-be7715b9136d)

**Comment by Samuwhale** [comment]
Can I get ahead and start writing code? Or would you like to discuss this PR and the check-list on Monday beforehand? @vankesteren

**Comment by qubixes** [comment]
@Samuwhale This PR will conflict with the other PR #275, so there might be some extra work involved if you do it right now.
