### ISSUE TITLE
implement UniquenessException from faker

### ISSUE THREAD

**Issue by vankesteren** [sodascience/metasyn#266]
See here: 
https://github.com/joke2k/faker?tab=readme-ov-file#unique-values

We might be able to implement this exception as well! Also, we are currently not using the unique feature in Faker for our uniquefakerdistribution, this might be a nice way to implement that.

**Comment by qubixes** [comment]
Do you mean to actually throw that particular error, or reimplement/reimport that error? I'm fine with keeping the same error, but it should be possible to do "from metasyn.exceptions import UniquenessException" or something like that.

**Comment by vankesteren** [comment]
Closing as "wontfix", will be handled in #265
