### ISSUE TITLE
Data type integration test with (almost) all datatypes in Polars

### ISSUE THREAD

**Issue by vankesteren** [sodascience/metasyn#274]
I think we should create a debug dataset which includes all (or all relevant) [data types in Polars](https://docs.pola.rs/user-guide/concepts/data-types/overview/). The debug dataset can be included in the demo files.

This can become the basis for an integration test (as previously mentioned in #270). The integration test should perform all steps in the pipeline and check whether the data types are appropriately reproduced.

![pipeline](https://github.com/sodascience/metasyn/blob/d96818a462b88823aba0ca63f8104745421474b5/docs/source/images/pipeline_basic.png?raw=true)

**Comment by qubixes** [comment]
Maybe it makes more sense to have a dataset repository, where we can keep adding more datasets (from the wild) to test? Or do you prefer it to be integrated into the main repository?
