### ISSUE TITLE
Separate our GH actions

### ISSUE THREAD

**Issue by vankesteren** [sodascience/metasyn#282]
Currently, we have 1 GH action that does everything. However, it might be nice to separate it out into several actions, together with our changes here: 
- #278 

For example, not run the full matrix all the time, not run the full documentation all the time, etc.

**Comment by vankesteren** [comment]
- Linting can be done on a single OS
- Plug-in testing should be done separately
- We should separate our optional-dependencies in pyproject.toml further to help this

**Comment by qubixes** [comment]
The one advantage of doing everything in one go is that is saves installation time. Let's see how much more it costs to separate the testing.
