### ISSUE TITLE
User test feedback

### ISSUE THREAD

**Issue by vankesteren** [sodascience/metasyn#307]
@Samuwhale (thanks!!) did user tests with several users unfamiliar with metasyn, and this is the most important feedback that came out of those tests.

- [x] #315
- [x] The most common problem: (all tested) users expected synthetic data generation parameters (e.g. Faker names, Unique, etc.) to be under ‘Generating Synthetic Data’ on the readme, as opposed to ‘Generating MetaFrames’. People only found the relevant page after using the search function, after already having looked at multiple wrong pages. -> Adding extra information on this page guiding users to the appropriate one is crucial. 
- [x] One user found VarSpec to be a confusing name, and suggested it being called something along the lines of ‘’extra generation parameters for variables’’
- [x] Python 3.12 does not allow straight up installation, and enforces users to install in a virtual environment -> this COULD potentially be mentioned as a small not in the install guide (e.g. “when using python 3.12 do …)
- [x] #328
- [x] The documentation redirect on github is broken (to learn more about how `metasyn` works, go to detailed overview in our documentation)
- [x] #309
- [x] One user tried using pandas instead of polars, and was confused about it not working. Maybe this should be made clearer somewhere - or a clear warning should be given about this when it occurs?

**Comment by qubixes** [comment]
I think we can close this issue.
