### ISSUE TITLE
Multinoulli distribution still gets chosen too much

### ISSUE THREAD

**Issue by vankesteren** [sodascience/metasyn#312]
I think we want to adjust the multinoulli distribution's information criterion a little more still, so that it gets chosen less. When we will start integrating audits of the json files into data generation workflows, it is going to be fairly annoying and not very confidence-inspiring to have about 45 parameters for a column with only 50 rows.

See reprex below, we can do this for different datatypes as well

```py
from metasyn import MetaFrame, MetaVar
from metasyn.distribution import DiscreteUniformDistribution
import matplotlib.pyplot as plt

mf = MetaFrame([MetaVar("yo", "int", DiscreteUniformDistribution(1, 300))], 50)

results = []
ssizes = range(10, 110, 10)
iter = 100
for n in ssizes:
    print(f"Computing multinoulli proportion for {n}")
    count = 0
    for i in range(iter):
        print(f"Iteration: {i}", end="\r")
        mf2 = MetaFrame.fit_dataframe(mf.synthesize(n), progress_bar=False)
        is_multinoulli = mf2["yo"].distribution.matches_name("core.multinoulli")
        if is_multinoulli:
            count += 1
    results.append(count / iter)


plt.plot(ssizes, results)
plt.xlabel("Synthetic data sample size")
plt.ylabel("Proportion of (wrongful) multinoulli distributions")
plt.title("Multinoulli inference for uniform distribution")
plt.show()
```

![multinouli_inference](https://github.com/user-attachments/assets/7710df82-de13-4216-9786-3f9ee049245f)

**Comment by vankesteren** [comment]
Update: based on discussion with @qubixes this problem seems to have magically disappeared. Let's keep an eye on this and maybe #274 could help detect these kinds of problems early?

**Comment by qubixes** [comment]
There are already statistical tests that are supposed to test this. I would say that the tests in #274 would be more about making sure that the data types are correct, not that the right distributions get chosen. It might be interesting to expand the statistical tests and make them more likely to catch these issues. The problem with the statistical tests is that if it fails 1% of the time and you have 50 tests, that is rather annoying.

**Comment by qubixes** [comment]
@vankesteren Btw, in many cases the multinoulli still gets chosen, for example in the space dataset. However, the problem is that this is statistically understandable, since it has a lot of the same values and then some tail. I don't think any of our distributions currently support this well except for the multinoulli one.
