### ISSUE TITLE
add automated tests for main methods, add domain dataset(s)

### ISSUE THREAD

**Issue by PetrKorab** [sodascience/metasyn#326]
Add automated tests covering the main Metasyn's methods, in line with [JOSS guidelines](https://joss.readthedocs.io/en/latest/review_criteria.html#tests). Also, please add tests for at least one domain dataset where you show the benefits of the programme. Make the data available to the reviewers, if possible. Thanks!

**Comment by qubixes** [comment]
@PetrKorab Thanks for your comments. Could you elaborate in more detail which automated tests you are missing? We currently have >90% coverage and they are tested automatically with GitHub actions. Which main methods do you find untested?

**Comment by PetrKorab** [comment]
@qubixes, Please add a link here to a folder with automated tests (JOSS submission). Thanks.

**Comment by qubixes** [comment]
The link to our test folder is https://github.com/sodascience/metasyn/tree/develop/tests for our development branch. I have added a medical dataset in #330, would that suffice as another domain dataset to you?

**Comment by vankesteren** [comment]
@PetrKorab we have extensive automated tests in our [tests](https://github.com/sodascience/metasyn/tree/develop/tests) folder, and we have now additionally documented them with docstrings based on your feedback.

Our tests include: 
- Unit tests for different methods on different data types, e.g., [test_continuous.py](https://github.com/sodascience/metasyn/blob/develop/tests/test_continuous.py)
- "integration" tests for all the included datasets in [our datasets folder](https://github.com/sodascience/metasyn/tree/develop/metasyn/demo), see [test_dataset.py](https://github.com/sodascience/metasyn/blob/develop/tests/test_dataset.py)
- tests for the command-line interface, see [test_cli.py](https://github.com/sodascience/metasyn/blob/develop/tests/test_cli.py)

In addition, our continuous integration includes linting, type checking, formatting, documentation building, and running the example jupyter notebook from our [examples](https://github.com/sodascience/metasyn/tree/develop/examples) folder. See [core-ci.yml](https://github.com/sodascience/metasyn/blob/develop/.github/workflows/core-ci.yml)

Data is available to everyone in this way: 

```py
from metasyn import demo_dataframe
df = demo_dataframe("hospital")
print(df)
```

```
┌────────────┬───────────────┬───────────────┬──────┬──────┬───────────────┐
│ patient_id ┆ date_admitted ┆ time_admitted ┆ type ┆ age  ┆ hours_in_room │
│ ---        ┆ ---           ┆ ---           ┆ ---  ┆ ---  ┆ ---           │
│ str        ┆ date          ┆ time          ┆ cat  ┆ i64  ┆ f64           │
╞════════════╪═══════════════╪═══════════════╪══════╪══════╪═══════════════╡
│ A5909X0    ┆ 2024-01-01    ┆ 10:30:00      ┆ IVT  ┆ null ┆ 3.633531      │
│ B4025X2    ┆ 2024-01-01    ┆ 11:23:00      ┆ IVT  ┆ 59   ┆ 6.932891      │
│ B6999X2    ┆ 2024-01-01    ┆ 11:58:00      ┆ IVT  ┆ 77   ┆ 1.970654      │
│ B9525X2    ┆ 2024-01-01    ┆ 16:56:00      ┆ MYE  ┆ null ┆ 1.620047      │
│ B0453X1    ┆ 2024-01-02    ┆ 11:50:00      ┆ IVT  ┆ null ┆ 3.344935      │
│ …          ┆ …             ┆ …             ┆ …    ┆ …    ┆ …             │
│ B3830X7    ┆ 2024-01-04    ┆ 16:03:00      ┆ CAT  ┆ 87   ┆ 3.87092       │
│ A7952X3    ┆ 2024-01-04    ┆ 18:00:00      ┆ IVT  ┆ 60   ┆ 4.332882      │
│ A0013X2    ┆ 2024-01-05    ┆ 10:06:00      ┆ CAT  ┆ null ┆ 2.133339      │
│ B2077X8    ┆ 2024-01-05    ┆ 10:43:00      ┆ IVT  ┆ null ┆ 6.026763      │
│ A4700X7    ┆ 2024-01-05    ┆ 14:53:00      ┆ MYE  ┆ 84   ┆ 6.193777      │
└────────────┴───────────────┴───────────────┴──────┴──────┴───────────────┘
```

I hope this answers your comment in a satisfactory way!

**Comment by PetrKorab** [comment]
Thanks for well addressing this

**Comment by PetrKorab** [comment]
Thanks for well addressing this issue!
