### ISSUE TITLE
Enforce uniqueness of variable names

### ISSUE THREAD

**Issue by vankesteren** [sodascience/metasyn#83]
We should not have multiple columns with the same name. Let's find ways of enforcing this
- in GMF specification
- building a check in metasynth

**Comment by qubixes** [comment]
I have tested it with csv files and polars and pandas. The result of reading in columns with the same names is polars/pandas dataframes with one renamed column name. Given that this should not really be an issue, I think we can close the issue. If anyone has problems with this particularly compared to metasyn, then they can reopen it.
